package com.lifevault.app.core.designsystem.color

import androidx.compose.ui.graphics.Color

// Section 4.1.1 — Brand scheme, light.
internal val LightPrimary = Color(0xFF1F4FD8)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFDCE4FF)
internal val LightOnPrimaryContainer = Color(0xFF0A1F5C)
internal val LightSecondary = Color(0xFF4F5B77)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFDDE3F7)
internal val LightOnSecondaryContainer = Color(0xFF0C1832)
internal val LightTertiary = Color(0xFF00796B)
internal val LightOnTertiary = Color(0xFFFFFFFF)
internal val LightTertiaryContainer = Color(0xFFB8F0E6)
internal val LightOnTertiaryContainer = Color(0xFF00201C)
internal val LightError = Color(0xFFBA1A1A)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val LightOnErrorContainer = Color(0xFF410002)
internal val LightBackground = Color(0xFFFBFBFE)
internal val LightSurface = Color(0xFFFBFBFE)
internal val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val LightSurfaceContainerLow = Color(0xFFF4F5FA)
internal val LightSurfaceContainer = Color(0xFFEEF0F6)
internal val LightSurfaceContainerHigh = Color(0xFFE8EAF1)
internal val LightSurfaceContainerHighest = Color(0xFFE2E4EC)
internal val LightOnSurface = Color(0xFF16181D)
internal val LightOnSurfaceVariant = Color(0xFF454A56)
internal val LightOutline = Color(0xFF767C8A)
internal val LightOutlineVariant = Color(0xFFC6CAD4)
internal val LightInverseSurface = Color(0xFF2B2D33)
internal val LightInverseOnSurface = Color(0xFFF0F1F7)
internal val LightInversePrimary = Color(0xFFB3C5FF)
internal val LightScrim = Color(0xFF000000)

// Section 4.1.2 — Brand scheme, dark.
internal val DarkPrimary = Color(0xFFB3C5FF)
internal val DarkOnPrimary = Color(0xFF002A78)
internal val DarkPrimaryContainer = Color(0xFF0F3CAB)
internal val DarkOnPrimaryContainer = Color(0xFFDCE4FF)
internal val DarkSecondary = Color(0xFFBDC6E0)
internal val DarkOnSecondary = Color(0xFF262F46)
internal val DarkSecondaryContainer = Color(0xFF3C465E)
internal val DarkOnSecondaryContainer = Color(0xFFDDE3F7)
internal val DarkTertiary = Color(0xFF7DD8C9)
internal val DarkOnTertiary = Color(0xFF003731)
internal val DarkTertiaryContainer = Color(0xFF005047)
internal val DarkOnTertiaryContainer = Color(0xFFB8F0E6)
internal val DarkError = Color(0xFFFFB4AB)
internal val DarkOnError = Color(0xFF690005)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)
internal val DarkBackground = Color(0xFF111318)
internal val DarkSurface = Color(0xFF111318)
internal val DarkSurfaceContainerLowest = Color(0xFF0C0E13)
internal val DarkSurfaceContainerLow = Color(0xFF191B21)
internal val DarkSurfaceContainer = Color(0xFF1D2026)
internal val DarkSurfaceContainerHigh = Color(0xFF282A30)
internal val DarkSurfaceContainerHighest = Color(0xFF33353B)
internal val DarkOnSurface = Color(0xFFE3E4EA)
internal val DarkOnSurfaceVariant = Color(0xFFC4C7D2)
internal val DarkOutline = Color(0xFF8E92A0)
internal val DarkOutlineVariant = Color(0xFF44474F)
internal val DarkInverseSurface = Color(0xFFE3E4EA)
internal val DarkInverseOnSurface = Color(0xFF2B2D33)
internal val DarkInversePrimary = Color(0xFF1F4FD8)
